# spring.application.name=vuestagram
spring:
  application:
    name: vuestagram

  # MariaDB 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/vuestagram
    username: root
    password: 123123
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # none 이외는 내장서버 시작/종료시 DB 초기화됨
    show-sql: true # 테스트서버 true, 런칭서버 false
    properties:
      hibernate:
        format_sql: true # 기본 포맷팅 여부
    defer-datasource-initialization: false # 레코드 데이터 백업 여부
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: never
      platform: all

# Sjf4j 설정
logging:
  file:
    name: classpath:logs/app.log
  level:
    root: info

# yml은 카멜이 적용안됨
config:
  jwt:
    issuer: lasjak@red.com
    type: JWT
    access-token-expiry: 1000000
    refresh-token-expiry: 1296000000
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-expiry: 1296000
    secret: 34h6baw46bw4tvgw4tgabwz34htbw4szybhe34ybh34tgv23a4tgv3w
    header-key: Authorization
    scheme: Bearer
    reiss-uri: /api/reissue-token
  file:
    real-file-path: C:/Users/kim37/AppData/Projects/Aworkspace/vuestagram/src/main # 절대 경로로 지정
    profile-path: /img/profile # 상대 경로로 지정, 저장 처리 코드에서 real-file-path를 연결하여 사용하는 식
    board-img-path: /img/boards # 상대 경로로 지정, 저장 처리 코드에서 real-file-path를 연결하여 사용하는 식